### ISSUE TITLE
Rubric and Summary

### ISSUE THREAD

**Issue by ulisigi** [somair/prj-rev-bwfs-tea-cozy#4]
### Criteria 1: HTML Structure  
* _Score Level:_ 4/4
* _Comment(s):_ HTML implementation enables proper use of flexbox.

HTML structure reflects the grouping and flow of content in the web browser.
 
### Criteria 2: Visual Layout
* _Score Level:_ 4/4
* _Comment(s):_ Layout matches the design spec in all sections 

(This includes a sticky header w/ no gap between it and top of viewport )
 
### Criteria 3: Use of Flexbox
* _Score Level:_ 4/4
* _Comment(s):_ Flexbox properties are correctly applied to flex containers and flex items throughout. 

Flexbox is used properly and is the primary way of positioning.
 
### Criteria 4: Implementation of Design Specification and Content
* _Score Level:_ 4/4
* _Comment(s):_ The page includes all style and content provided in the design specification.

(For example, anchor colors match the design spec.)
 
### Overall Score: 16/16
Your project Exceeds Expectations - way to go! The difficulty of this project, especially in the layout, is much higher than in the Dasmoto project submitted first. You did a great job duplicating the design specification. Nice use of comments in both your HTML and CSS. I recommend utilizing more semantic elements in your HTML to further improve readability of your code, as well as improve the accessibility and SEO of the page.

Here's a reference for semantic elements:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element

Here's an article about semantic elements and accessibility:
https://24ways.org/2017/accessibility-through-semantic-html/

Overall, excellent job on this project. For extra practice, use the skills that you've learned in the first half of this course to start building a personal site to showcase your projects and skills. In Unit 5, you'll be learning to make your sites mobile friendly and responsive to different screen sizes. For extra practice of those skills, try making Tea Cozy mobile friendly as well. Keep up the great work, and happy coding!

**Comment by somair** [comment]
Thank you! Your comments are very thoughtful and of practical value. I am looking forward to media queries and making my web pages responsive to various different screen sizes. Thank you again!
